In [9]:
# DATA CREATION

In [1]:
#  random_state RANDOM_STATE
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42) 


<h2> # RANDOM_STATE

random_state simply sets a seed to the random generator, 
so that your train-test splits are always deterministic. If you don't set a seed, it is different each time.
</h2>

In [3]:
# SEED

# random_State = 42
# 42, 786, 12345
# 42 similar to 786 as a belief

In [5]:
from numpy import random

x = random.randint(100)

print(x)

42


In [7]:
from numpy import random
# Float 0 to 1
x = random.rand()

print(x)

0.3805645056294995


In [8]:
from numpy import random
# ARRAY 
x=random.randint(100, size=(20))

print(x)

[ 2 76  0 14 85 35 92  1 47 82 25 44 45 65 22 66 83 69 69 76]


In [11]:
from numpy import random
# ROWS, COLUMNS
x = random.randint(100, size=(3, 5))

print(x)

[[17 35 69 18 25]
 [62 89 44 55  0]
 [48 12 42 17 30]]


In [13]:
# Generate Random Number From Array
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

9


In [14]:
from numpy import random
# ROw, COLUMN
x = random.choice([0,1], size=(1, 100))

print(x)

[[1 1 0 1 0 0 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 1
  1 0 1 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 1
  0 0 1 0 0 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1 0 1 1 1 1 0 0]]


In [15]:
# Choice with probability ( sum of prob = 1)
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 7 3 7 7 7 7 7 3 5 5 7 7 7 7 7 3 7 7 7 5 7 5 5 5 5 3 3 7 7 7 7 7 7 7
 7 3 3 7 5 5 7 5 5 5 7 7 7 7 7 5 3 7 7 7 3 3 3 7 7 7 5 7 5 7 7 7 7 7 5 7 7
 5 7 7 7 5 3 7 3 5 7 5 7 7 7 7 7 7 3 3 7 7 7 3 7 5 5]


In [17]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[1 5 2 3 4]


In [20]:
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [22]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [23]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [25]:
# Reshaping means changing the shape of an array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

#The copy returns None.
#The view returns the original array.

None
[1 2 3 4 5]


In [31]:
#copy is a new array, and the view is just a view of the original array.

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [33]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [34]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
